name: Deploy to prod

on:
  push:
    branches:
      - master
    paths:
      - handlers/*
      - constants.js
      - serverless.yml
      - package.json
      - package-lock.json

jobs:
  deploy-prod:
    uses: ./.github/workflows/serverless-deploy.yaml
    with:
      ENVIRONMENT: prod