name: Deploy to prod

on:
  workflow_dispatch:
  schedule:
    # every monday at 6:00 AM UTC
    - cron: '0 6 * * 1'

jobs:
  deploy-prod:
    uses: ./.github/workflows/serverless-deploy.yaml
    permissions:
      id-token: write
      contents: read
    with:
      ENVIRONMENT: prod