name: Deploy to staging

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    uses: ./.github/workflows/serverless-deploy.yaml
    permissions:
      id-token: write
      contents: read
    secrets:
      AWS_DEPLOYER_ROLE: ${{ secrets.AWS_DEPLOYER_ROLE }}
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
    with:
      ENVIRONMENT: staging