name: Deploy to prod

on:
  workflow_dispatch:
  schedule:
    # every 2 hours
    - cron: '0 */2 * * *'

jobs:
  deploy-prod:
    uses: ./.github/workflows/serverless-deploy.yaml
    permissions:
      id-token: write
      contents: read
    secrets:
      AWS_DEPLOYER_ROLE: ${{ secrets.AWS_DEPLOYER_ROLE }}
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
    with:
      ENVIRONMENT: prod
  
  run-perf-smoke:
    uses: ./.github/workflows/run-performance-test.yaml
    permissions:
      id-token: write
      contents: read
    secrets:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      ARTILLERY_CLOUD_API_KEY: ${{ secrets.ARTILLERY_CLOUD_API_KEY }}
    with:
      ENVIRONMENT: prod
      TEST_TYPE: smoke
      VERSION: ${{ github.sha }}