name: Run tests on Branch

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test

  deploy-ephemeral:
    uses: ./.github/workflows/serverless-deploy.yaml
    needs: run-unit-tests
    permissions:
      id-token: write
      contents: read
    secrets:
      AWS_DEPLOYER_ROLE: ${{ secrets.AWS_DEPLOYER_ROLE }}
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
    with:
      ENVIRONMENT: ${{ github.actor }}-${{ github.event.pull_request.number || github.run_id }}
      SHOULD_SEED_DB: true

  run-functional-tests:
    needs: deploy-ephemeral
    runs-on: ubuntu-latest
    steps:
      - name: Run functional tests
        run: echo "Running functional tests against ${{ needs.deploy-ephemeral.outputs.SERVICE_URL }}"
        env:
          SERVICE_URL: ${{ needs.deploy-ephemeral.outputs.SERVICE_URL }}

  run-perf-regression:
    uses: ./.github/workflows/run-performance-test.yaml
    needs: [deploy-ephemeral, run-functional-tests]
    permissions:
      id-token: write
      contents: read
    secrets:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      ARTILLERY_CLOUD_API_KEY: ${{ secrets.ARTILLERY_CLOUD_API_KEY }}
    with:
      ENVIRONMENT: custom
      TEST_TYPE: regression
      VERSION: ${{ github.sha }}
      SERVICE_URL: ${{ needs.deploy-ephemeral.outputs.SERVICE_URL }}
  
  teardown-ephemeral-env:
    uses: ./.github/workflows/stack-delete.yaml
    needs: run-perf-regression
    permissions:
      id-token: write
      contents: read
    secrets:
      AWS_DEPLOYER_ROLE: ${{ secrets.AWS_DEPLOYER_ROLE }}
    with:
      ENVIRONMENT: ${{ github.actor }}-${{ github.event.pull_request.number }}