name: Seed DynamoDB

on:
  workflow_call:
    inputs:
      DEPLOYMENT_REGION:
        description: 'AWS region to deploy to'
        required: false
        default: 'us-east-1'
        type: string
      ENVIRONMENT:
        description: 'Environment to deploy to'
        required: true
        type: string

permissions:
    id-token: write
    contents: read

jobs:
  deploy-to-env:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Seed DynamoDB - ${{ github.event.inputs.ENVIRONMENT }}
      run: npm run seed
      env:
        DEPLOYMENT_REGION: ${{ github.event.inputs.DEPLOYMENT_REGION }}
        ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT }}d